CREATE TABLE Users (
	UserID INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    Email VARCHAR(255),
    GID VARCHAR(255),
    GroupID INT,
    FOREIGN KEY (GroupID) REFERENCES Groups.GroupID
)

CREATE TABLE Groups (
	GroupID INT PRIMARY KEY AUTO_INCREMENT,
    Admin BINARY
)
